### ISSUE TITLE
fix version

### ISSUE THREAD

**Issue by lobnico** [Js41637/Steam-Anti-Spam-Bot#1]

**Comment by Js41637** [comment]
Interesting. I use to only use the bot for some groups I was in for a friend but then Valve got pretty good at detecting them so I just stopped it and haven't used it in a while.

Not sure why you deleted the comment but I still see it because all comments on my repos get proxied to Slack.

**Comment by lobnico** [comment]
Oh, I made a PR instead ^^
We got around 30 thread opened by spammers everyday, valve look
overwhelmed or something
so your code comes in really handy !
